const fs=require('fs'),assert=require('assert');
const chats=fs.readFileSync('js/features/chats.js','utf8');
const games=fs.readFileSync('js/chat/room-games.js','utf8');
const index=fs.readFileSync('index.html','utf8');
assert(chats.includes('sorted.forEach(message=>{if(message?.type==="game")MiniTalk.Chat.RoomGames?.ingest?.(message)})'), 'fresh render must ingest complete game timeline before visibility decisions');
assert(games.includes('sessionGames:new Map()'), 'popup sessions must retain roomId per game');
assert(games.includes('d.sessionGames.set(String(message.game.id),String(d.roomId||message.roomId||""))'), 'opened game room mapping missing');
assert(games.includes('for(const [id,rid] of sessions)if(rid)await leaveActiveDesktopGame(rid,id)'), 'explicit popup close does not leave every tracked room/game pair');
assert(games.includes('sessions.forEach(([gameId,roomId])=>{if(roomId)leaveActiveDesktopGame(roomId,gameId)'), 'native popup close does not leave every tracked room/game pair');
assert(games.includes('disabled:ended,"aria-disabled":String(ended)'), 'terminal recent games must not be reopenable');
assert(games.includes('if(!ended)b.onclick=()=>showDesktopMessage(msg)'), 'ended recent game still has open handler');
assert(index.includes('js/chat/room-games.js?v=26'), 'room-games cache version stale');
assert(index.includes('js/features/chats.js?v=64.5.25'), 'chats cache version stale');
console.log('CHAT_ROOM_GAMES_FRESH_RENDER_POPUP_SESSION_AUDIT_OK');
