const fs=require('fs'),assert=require('assert');
const src=fs.readFileSync('js/chat/room-games.js','utf8');
assert(src.includes('try{rolePanel.__mafiaOnReveal?.()}catch{}'),'auto role reveal must rebuild phase UI');
assert(src.includes('phaseMsg.game.winner==="citizen"?"시민 승리":"게임 중단"'),'aborted mafia game must not be labelled citizen win');
const inviteCardSrc=src.slice(src.indexOf('function inviteCard('),src.indexOf('function gameDocuments('));
assert(inviteCardSrc.includes('canOpenJoin=!isHost&&g.openJoin!==false'),'open-join participant path missing');
assert(!inviteCardSrc.includes('requestInviteDecline(')&&!inviteCardSrc.includes('text:"거절"'),'compact invite card must not render a decline button for non-invited open-join users');
assert(inviteCardSrc.includes('if(final)return card;'),'final invite card must stop before rendering participation actions');
assert(src.includes("function gameWindow()"),'popup-aware window helper missing');
assert(src.includes("gamePrompt('프로모션"),'chess promotion prompt must target game popup');
assert(src.includes("gameConfirm('체스 게임에서 기권할까요?')"),'chess resign confirm must target game popup');
assert(src.includes('gameConfirm("이 마피아 게임에서 나갈까요?'),'mafia leave confirm must target game popup');
assert(src.includes('clearGameVolatileState(gameId);state.messages.delete(gameId)'),'finished game volatile state is not cleared');
assert(src.includes('.normalize("NFKC")'),'legacy nickname dedupe should normalize equivalent text');
console.log('CHAT_ROOM_GAMES_DEEP_LIFECYCLE_AUDIT_OK');
