const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const chats=read('js/features/chats.js'),rt=read('js/adapters/realtime.js'),shell=read('js/ui/shell.js'),guard=read('js/ui/interaction-guard.js'),css=read('css/app.css'),feedCss=read('css/features/feed-classinfo-weekly.css'),html=read('index.html'),sw=read('sw.js'),app=read('js/app.js');
ok(chats.includes('function waitForRoomList()')&&chats.includes('markRoomListReady(view)'),'first room-list paint readiness hook missing');
ok(chats.includes('roomSnapshotReceived=true')&&chats.includes('!ready||visible>0'),'empty room state can flash before first room snapshot');
ok(shell.includes('const firstRoomListPaint=MiniTalk.Features.Chats?.waitForRoomList?.()')&&shell.includes('endInitialLoading()'),'initial loading is not tied to actual room-list paint');
ok(rt.includes('hydrateRoomSummaryCache()')&&rt.includes('persistRoomSummaryCacheSoon()'),'local room-summary warm cache missing');
ok(!rt.includes('room.summaryCache')||!rt.includes('once("value")/*room-summary-cache*/'),'room-summary warm cache must not add server reads');
ok(chats.includes('function scrollToLatest(list)')&&chats.includes('scrollToLatest(list)'),'chat entry does not force latest message position');
ok(css.includes('scroll-behavior:auto')&&css.includes('.message-list::-webkit-scrollbar')&&css.includes('scrollbar-gutter:stable'),'native draggable chat scrollbar / no-smooth-race CSS missing');
ok(guard.includes('nativeScrollSurface')&&guard.includes('.message-list,.conversation-list'),'interaction guard still blocks native scrollbar surface');
ok(feedCss.includes('bottom:calc(-20px + 58px')&&feedCss.includes('bottom:calc(-20px + 54px'),'feed + button was not lowered consistently');
ok(html.includes('css/app.css?v=64.5.23')&&html.includes('css/features/feed-classinfo-weekly.css?v=65.0.31')&&html.includes('js/adapters/realtime.js?v=64.5.47')&&html.includes('js/ui/shell.js?v=64.5.34')&&html.includes('js/ui/interaction-guard.js?v=64.5.1')&&html.includes('js/features/chats.js?v=64.5.25')&&html.includes('js/app.js?v=64.5.46'),'cache-bust versions stale');
ok(sw.includes('moaru-moa-dialogue-fusion-final')&&app.includes('sw.js?v=64.5.60'),'service-worker cache version stale');
console.log('CHAT_SCROLL_INITIAL_LIST_OK');
