const fs=require('fs'),assert=require('assert');
const src=fs.readFileSync('js/chat/room-games.js','utf8');
const index=fs.readFileSync('index.html','utf8');
assert(src.includes('phaseResolving:new Set()'),'mafia phase resolution lock missing');
assert(src.includes('function resolveMafiaPhaseOnce('),'shared mafia phase resolver missing');
assert(src.includes('if(inviteFinalMessage(gameId))return;'),'late invite accepts can still create post-final packets');
assert(src.includes('remaining.length<4'),'pre-role mafia drop below minimum can still hang');
assert(src.includes('"host-left-before-start"')&&src.includes('"not-enough-before-start"')&&src.includes('"left-during-role-setup"'),'pre-role mafia termination reasons missing');
assert(src.includes("function chessTerminal(gameId){const ends=allOf(gameId,'chess-end')"),'deterministic chess terminal selection missing');
assert(src.includes("sort((a,b)=>String(a.id||'').localeCompare(String(b.id||'')))[0]"),'chess terminal selection still depends on receive order');
assert(src.includes('if(!desktopGameMode()&&g.kind==="ladder")return ladderCard(g)'),'mobile ladder result must remain playable instead of collapsing immediately to terminal card');
assert(index.includes('js/chat/room-games.js?v=26'),'room-games cache version stale');
console.log('CHAT_ROOM_GAMES_FORENSIC_RACE_AUDIT_OK');
