const fs=require("fs"),path=require("path"),root=path.resolve(__dirname,"..");
const read=p=>fs.readFileSync(path.join(root,p),"utf8"),ok=(v,m)=>{if(!v)throw new Error(m)};
const cache=read("js/adapters/data-cache.js"),rt=read("js/adapters/realtime.js"),feed=read("js/features/feed.js"),index=read("index.html"),sw=read("sw.js"),rules=JSON.parse(read("database.rules.json"));
ok(cache.includes('indexedDB.open(DB_NAME,DB_VERSION)')&&cache.includes('CHAT_MAX=100'),"IndexedDB shared data cache missing");
ok(cache.includes('MAX_AGE=30*24*60*60*1000')&&cache.includes('CLEAN_INTERVAL=24*60*60*1000'),"automatic cache retention/maintenance missing");
ok(cache.includes('async function getMessages(roomId,limit=CHAT_MAX)')&&cache.includes('async function putMessage(roomId,message)'),"chat cache API missing");
ok(index.includes('js/adapters/data-cache.js?v=64.5.25'),"data cache script not loaded");
ok(sw.includes('"./js/adapters/data-cache.js"'),"data cache module missing from offline core");
ok(rt.includes('MiniTalk.DataCache?.getMessages?.(cacheRoom,CHAT_PAGE_SIZE)')&&rt.includes('base.limitToLast(CHAT_PAGE_SIZE)')&&rt.includes('base.startAt(lastTs)')&&rt.includes('`${user.user_id}|${roomId}`'),"chat should use user-scoped cached history then Firebase delta");
ok(rt.includes('startProfileCollection')&&rt.includes('orderByChild("updatedAt").startAt(latest+1)'),"profile delta sync missing");
ok(feed.includes('MiniTalk.DataCache?.get?.(MEDIA_CACHE,id,null)')&&feed.includes('MiniTalk.DataCache?.put?.(MEDIA_CACHE,id,media'),"feed media cache-first loading missing");
ok(feed.includes("cachedPostRows")&&feed.includes("takeCachedOlder(oldest,PAGE_SIZE)"),"feed older pages must use cached posts before server reads");
ok(feed.includes('MiniTalk.DataCache?.get?.(THUMB_CACHE,id,"')&&feed.includes('cloudGet(`${MEDIA_PATH}/${id}/thumbnail`'),"video thumbnail cache-first loading missing");
ok(feed.includes('MiniTalk.Realtime.cloudQueryChildren(POSTS_PATH')&&feed.includes('cloudSubscribeDelta'),"feed metadata cache reconciliation/delta sync missing");
ok(rules.rules.profiles?.[".indexOn"]?.includes("updatedAt"),"legacy profile updatedAt index missing");
ok(rules.rules.moaru?.v3?.profiles?.[".indexOn"]?.includes("updatedAt"),"v3 profile updatedAt index missing");
ok(rules.rules.moaru?.v3?.feedState?.posts?.[".indexOn"]?.includes("updatedAt"),"feed updatedAt index missing");
ok(!rt.includes("avatar:senderProfile.avatar"),"chat messages must reference cached profiles instead of duplicating avatar data");
ok(feed.includes("avatarForPost(post)")&&!feed.includes("avatar:profile.avatar"),"feed posts must reference cached profiles instead of duplicating avatar data");
console.log("DEVICE_DATA_CACHE_OK");
