import {weaponPose} from '../games/dungeonwarden/shared/weapon-poses.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {DungeonGame} from '../cf-worker/src/dungeon/engine.mjs';import {weaponSkill} from '../games/dungeonwarden/shared/weapon-skills.mjs';
function setup(){const g=new DungeonGame({seed:42,mode:'dungeon',bots:0});g.entities=g.entities.filter(e=>e.id==='local');g.map.obstacles=[];g.chests=[];g.loot=[];const e=g.entities[0];e.x=8;e.y=12;g.map.bodies=g.entities;return [g,e];}
const step=(g,n)=>{for(let i=0;i<n;i++)g.step(.05);};
test('high rarity weapons have concept skills while low rarity staff uses its own elemental skill',()=>{const [g]=setup(),weapons=g.itemCatalog.filter(i=>i.kind==='main');const high=weapons.filter(i=>i.tier>=2);assert.ok(new Set(high.map(i=>weaponSkill(i).kind)).size>=15);for(const i of weapons.filter(i=>i.tier===1&&i.visual.shape==='staff'))assert.equal(weaponSkill(i).kind,i.type);assert.equal(weaponSkill(high.find(i=>i.appearance==='giant_baguette')).kind,'breadline');});
test('whirlwind moves and damages repeatedly, releases promptly and caps at two seconds',()=>{const [g,e]=setup();e.equipment.main=g.itemCatalog.find(i=>i.kind==='main'&&i.type==='greatsword'&&i.tier===1);g.input('local',{mx:1,special:true,aimX:20,aimY:12});step(g,10);assert.ok(e.whirl);assert.ok(e.x>8);const spins=g.effects.filter(f=>f.kind==='spin');assert.ok(spins.length>0);g.input('local',{mx:1,special:false});step(g,1);assert.equal(e.whirl,null);e.cooldowns.special=0;g.input('local',{mx:1,special:true});step(g,45);assert.equal(e.whirl,null);});
test('bread erupts at one-step spacing, deals damage and stops at obstruction',()=>{const [g,e]=setup();e.facing=0;e.equipment.main=g.itemCatalog.find(i=>i.appearance==='giant_baguette');g.special(e,{kind:'breadline',damage:30,x:16,y:12,slot:'main'});assert.equal(g.zones.length,5);assert.deepEqual(g.zones.map(z=>z.x),[9,10,11,12,13]);const monster=g.addMonster('slime',0,g.map.rooms[0],{x:10,y:12});monster.aiAt=999;g.time=.3;g.updateZones();assert.ok(monster.hp<monster.maxHp);g.zones=[];g.map.obstacles=[{x:10.5,y:10,w:1,h:4}];g.special(e,{kind:'breadline',damage:30,x:16,y:12,slot:'main'});assert.equal(g.zones.length,2);});
test('all high rarity skills execute without non-finite attacks; dash is exposed for client trails',()=>{const [g,e]=setup();for(const i of g.itemCatalog.filter(i=>i.kind==='main'&&i.tier>=2)){e.equipment.main=i;g.special(e,{kind:weaponSkill(i).kind,x:15,y:12,damage:20,slot:'main'});for(const p of [...g.projectiles,...g.zones])assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.y));}e.whirl=null;g.input('local',{mx:1,sprint:true,aimX:20,aimY:12});step(g,1);assert.equal(g.snapshot('local').me.dashing,true);g.input('local',{});step(g,1);assert.equal(g.snapshot('local').me.dashing,false);});

test('dash partially recovers but full three seconds locks it for three seconds',()=>{const [g,e]=setup();g.input('local',{mx:1,sprint:true,aimX:30,aimY:12});step(g,20);assert.ok(Math.abs(e.dash-2)<.001);g.input('local',{});step(g,10);assert.ok(Math.abs(e.dash-2.5)<.001);g.input('local',{mx:1,sprint:true});step(g,50);assert.equal(e.dash,0);assert.ok(e.dashRecovery>2.9);step(g,30);assert.equal(e.dashing,false);assert.ok(e.dashRecovery>1.4);g.input('local',{});step(g,31);assert.equal(e.dashRecovery,0);assert.equal(e.dash,3);});

test('basic attacks chain three hits, advance with body collision and reset after a pause',()=>{const [g,e]=setup();e.equipment.main=g.itemCatalog.find(i=>i.type==='sword'&&i.tier===0);e.facing=0;const start=e.x;for(const n of [1,2,3,1]){e.cooldowns.attack=0;g.attack(e,{aimX:20,aimY:12});assert.equal(e.combo,n);g.time+=.6;}assert.ok(e.x>start);g.time+=1.6;e.cooldowns.attack=0;g.attack(e,{});assert.equal(e.combo,1);g.map.obstacles=[{x:e.x+.5,y:e.y-1,w:1,h:2}];const x=e.x;e.cooldowns.attack=0;g.attack(e,{});assert.ok(e.x<=x+.05);});

test('two-handed attacks use two combos and hit several targets; ranged has no combo; special cancels chain',()=>{const [g,e]=setup();e.equipment.main=g.itemCatalog.find(i=>i.type==='greatsword'&&i.tier===1);e.facing=0;const a=g.addMonster('slime',0,g.map.rooms[0],{x:10,y:11.5}),b=g.addMonster('slime',0,g.map.rooms[0],{x:10,y:12.5});a.x=10;a.y=11.5;b.x=10;b.y=12.5;for(const n of [1,2,1]){e.cooldowns.attack=0;g.attack(e,{});assert.equal(e.combo,n);g.time+=.8;}assert.ok(a.hp<a.maxHp&&b.hp<b.maxHp);g.attack(e,{},true);assert.equal(e.combo,0);assert.ok(e.whirl);e.whirl=null;e.cooldowns.attack=0;e.equipment.main=g.itemCatalog.find(i=>i.type==='meteor');g.attack(e,{});assert.equal(e.combo,0);assert.equal(g.projectiles.at(-1).remaining,16*1.2);});

test('holding melee basic does not automatically chain; a new press advances the combo',()=>{const [g,e]=setup();e.equipment.main=g.itemCatalog.find(i=>i.type==='sword'&&i.tier===0);g.input('local',{attack:true,aimX:20,aimY:12});step(g,16);assert.equal(e.combo,1);g.input('local',{attack:false});step(g,1);g.input('local',{attack:true,aimX:20,aimY:12});step(g,1);assert.equal(e.combo,2);});

test('monster ranged shot warns before firing and retains its locked aim',()=>{const [g,e]=setup();const m=g.addMonster('lich',0,g.map.rooms[0],{x:15,y:12});m.facing=Math.PI;g.attack(m,{aimX:e.x,aimY:e.y});assert.equal(g.projectiles.length,0);assert.equal(m.cast.kind,'monster-shot');const c=m.cast;m.cast=null;g.special(m,c);assert.equal(g.projectiles.length,1);assert.equal(g.projectiles[0].angle,Math.PI);});
test('weapon resting and walking poses differ by family without changing gameplay',()=>{const kinds=['dagger','sword','axe','mace','greatsword','hammer','bow','meteor'];assert.equal(new Set(kinds.map(k=>JSON.stringify(weaponPose(k)))).size,8);for(const k of kinds){const p=weaponPose(k,true,1);assert.ok(Number.isFinite(p.angle)&&Number.isFinite(p.height));assert.notEqual(p.angle,weaponPose(k,false,1).angle);}});


