const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8'),ok=(v,m)=>{if(!v)throw new Error(m)};
const rt=read('js/adapters/realtime.js'),chats=read('js/features/chats.js'),css=read('css/app.css'),feedcss=read('css/features/feed-classinfo-weekly.css'),html=read('index.html'),sw=read('sw.js'),app=read('js/app.js');
ok(rt.includes('function parseLegacyParticipantList(value)'),'legacy room participant parser missing');
ok(rt.includes('value.participants??value.memberNames??value.member_names'),'legacy room member formats are not normalized');
ok(rt.includes('function migrateAllRoomSummaries()')&&rt.includes('async function ensureCurrentUserRoomIndex()'),'legacy room summary migration/index fallback missing');
ok(rt.includes('function publishRooms(){persistRoomSummaryCacheSoon();emit("rooms",{...(roomListRequested?roomDirectoryCache:roomsCache)})}'),'member/group room cache publishing missing');
ok(rt.includes('function startMemberRoomIndexSubscription()')&&rt.includes('query.on("child_changed",upsert'),'room summary live updates should use member summaries plus group-on-demand stream');
ok(chats.includes('function roomPreview(room)')&&chats.includes('MiniTalk.Chat.Emoji.appendText(text,node,room?.lastMessageEmoticon||"")'),'room list custom emoticon preview missing');
ok(rt.includes('lastMessageEmoticon:message.emoticon||null'),'room metadata does not preserve custom emoticon code');
ok(css.includes('.conversation-preview .chat-emoticon{width:22px!important;height:22px!important'),'room-list emoticon is not compact');
ok(feedcss.includes('background:color-mix(in srgb,#d5d9e1 48%,transparent)'),'feed FAB is not translucent light gray');
ok(feedcss.includes('bottom:calc(-20px + 58px'),'feed FAB was not lowered further');
ok(html.includes('css/app.css?v=64.5.23')&&html.includes('feed-classinfo-weekly.css?v=65.0.31')&&html.includes('realtime.js?v=64.5.47')&&html.includes('features/chats.js?v=64.5.25')&&html.includes('app.js?v=64.5.46'),'v5.22 cache versions stale');
ok(sw.includes('moaru-moa-dialogue-fusion-final')&&app.includes('sw.js?v=64.5.60'),'v5.22 service worker version stale');
console.log('LEGACY_ROOM_EMOJI_UI_OK');
