const fs=require("fs"),path=require("path"),root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const ok=(v,m)=>{if(!v)throw new Error(m)};
const auth=read("js/features/auth.js"),windowMode=read("js/adapters/window-mode.js"),realtime=read("js/adapters/realtime.js"),index=read("index.html"),sw=read("sw.js");
ok(auth.includes("function returnToLogin()"),"remembered-session return-to-login path is missing");
ok(auth.includes('MiniTalk.Store.set("user",null)')&&auth.includes('if(host)render(host)'),"PiP close does not clear runtime user and rerender login");
const returnBlock=auth.slice(auth.indexOf("function returnToLogin()"),auth.indexOf("function logout()"));
ok(!returnBlock.includes("MiniTalk.Persistence.remove(KEY)"),"return-to-login deletes the remembered login session");
ok(windowMode.includes("MiniTalk.Features.Auth?.returnToLogin?.()")&&!windowMode.includes("MiniTalk.Features.Auth?.logout?.()"),"PiP close still performs a real logout");
ok(realtime.includes("ROOM_SUMMARY_CACHE_MAX_IDLE=30*24*60*60*1000"),"room summary idle TTL is not 30 days");
ok(realtime.includes("purgeStaleRoomSummaryCaches()")&&realtime.includes("localStorage.removeItem(storageKey)"),"stale room summary cache sweep is missing");
ok(realtime.includes("lastAccessedAt:Date.now()")&&realtime.includes("idle>=ROOM_SUMMARY_CACHE_MAX_IDLE"),"room summary cache is not based on last use");
ok(index.includes("js/adapters/realtime.js?v=64.5.47")&&index.includes("js/adapters/window-mode.js?v=64.5.40")&&index.includes("js/features/auth.js?v=64.5.35"),"updated scripts are not cache-busted");
ok(sw.includes("moaru-moa-dialogue-fusion-final"),"service-worker cache version is stale");
console.log("PIP_SESSION_IDLE_CACHE_OK");
