const fs=require('fs');
const read=file=>fs.readFileSync(file,'utf8');
const tools=read('js/features/tools.js'),config=read('js/config.js'),chats=read('js/features/chats.js'),capture=read('js/tools/capture.js');
const shell=read('js/ui/shell.js'),profile=read('js/tools/profile-editor.js'),css=read('css/app.css'),html=read('index.html'),sw=read('sw.js'),app=read('js/app.js');
function ok(value,message){if(!value)throw new Error(message)}
ok(!tools.includes('id: "playground"'),'playground must not remain in main tools grid');
ok(config.includes('{name:"온라인 놀이터",url:"https://langret100.github.io/multiroom-playground/"}'),'playground related link is missing');
ok(tools.includes('id: "lookalike"')&&tools.includes('title: "닮은 생물 찾기"'),'lookalike tool replacement missing');
ok(!tools.includes('title: "화면 캡처"')&&!tools.includes('capture: () =>'),'obsolete capture tool card remains');
ok(chats.includes('addAction("▣","캡처"')&&chats.includes('Capture.captureAndSend(roomId)'),'chat capture attachment is missing its explicit room target');
ok(!chats.includes('addAction("▦","QR"'),'QR attachment action still exists');
ok(chats.includes('MiniTalk.Realtime.isRoomMember(room)?"🔓":"🔒"')&&chats.includes('"참여 중인 비밀번호방":"잠긴 비밀번호방"'),'password room lock state icon does not reflect membership');
ok(capture.includes('async function captureAndSend(roomId = "")')&&capture.includes('String(roomId || MiniTalk.Store.get("activeRoom") || "")'),'capture service does not prioritize the open room');
ok(shell.includes('options.hostClass')&&shell.includes('options.modalClass'),'modal class options are missing');
ok(profile.includes('hostClass: "profile-modal-host"')&&chats.includes('hostClass:"profile-modal-host"'),'profile edit or view modal is not centered');
ok(css.includes('.modal-host{align-items:center;padding:14px}')&&css.includes('.header-create-button{font-size:23px!important')&&css.includes('.header-search-button::before{content:"⌕"')&&css.includes('transform:translate(-50%,-68%)'),'mobile modal centering or header icon sizing is missing');
ok(chats.includes('text:"⌕","aria-label":"검색"')&&chats.includes('class:"search-glyph",text:"⌕"'),'original search glyph was not preserved');
ok(css.includes('.room-lock-badge{right:-5px;bottom:-4px;min-width:0;width:auto;height:auto;border:0;border-radius:0;background:transparent;box-shadow:none'),'room lock badge still has a circular overlay');
ok(html.includes('js/features/chats.js?v=64.5.25'), 'stale cache version for js/features/chats.js');
ok(html.includes('js/features/auth.js?v=64.5.35'),'stale cache version for js/features/auth.js');
ok(html.includes('js/app.js?v=64.5.46'),'stale cache version for js/app.js');
ok(html.includes('css/app.css?v=64.5.23'),'stale cache version for css/app.css');
ok(html.includes('js/ui/shell.js?v=64.5.34'),'stale cache version for js/ui/shell.js');
ok(html.includes('js/tools/profile-editor.js?v=64.4.2'),'stale cache version for js/tools/profile-editor.js');
ok(html.includes('js/features/tools.js?v=64.5.15'),'stale cache version for js/features/tools.js');
ok(html.includes('js/tools/capture.js?v=64.5.8'),'stale cache version for js/tools/capture.js');
ok(html.includes('js/chat/linkify.js?v=64.5.8'),'stale cache version for js/chat/linkify.js');
ok(html.includes('css/chat-link-capture-polish.css?v=64.5.8'),'chat link polish stylesheet is missing');
ok(sw.includes('moaru-moa-dialogue-fusion-final')&&app.includes('sw.js?v=64.5.60'),'service worker v64.5.14 cache update is missing');
ok(shell.includes('modal-close-button')&&css.includes('.modal-close-button::before')&&css.includes('transform:translateY(-1px)'),'common close glyph is not visually centered');
ok(css.includes('.mine .bubble{background:var(--accent);color:var(--accent-ink);border-color:var(--accent)')&&css.includes('border-color:var(--accent);box-shadow:none'),'outgoing bubble still has a bright transparent ring');
ok(chats.includes('composer-icon composer-attach-button')&&css.includes('.composer-attach-button::before{content:"+"')&&css.includes('font-size:25px'),'composer attach button is not visibly centered and enlarged');
ok(css.includes(':root[data-window-mode="standalone"] .workspace{grid-template-columns:1fr;grid-template-rows:1fr 56px}')&&css.includes('grid-template-rows:1fr calc(56px + env(safe-area-inset-bottom,0px))'),'bottom navigation final height is stale');
console.log('PLAYGROUND_CAPTURE_MODAL_UI_OK');
