const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const realtime=fs.readFileSync(path.join(root,'js/adapters/realtime.js'),'utf8');
const shell=fs.readFileSync(path.join(root,'js/ui/shell.js'),'utf8');
const chats=fs.readFileSync(path.join(root,'js/features/chats.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
if(realtime.includes('await Promise.all(initialData)')||realtime.includes('const initialData=[]'))throw new Error('legacy Firebase first-snapshot barrier still blocks the workspace');
if(!realtime.includes('startProfileCollection(legacyProfilesRef,"legacy"')||!realtime.includes('startProfileCollection(currentProfilesRef,"current"'))throw new Error('cache-first background profile bootstrap is missing');
if(!shell.includes('const realtimeReady=MiniTalk.Realtime.init(user).then(')||shell.includes('await MiniTalk.Realtime.init(user)'))throw new Error('realtime bootstrap still blocks chat workspace');
if(!chats.includes('MiniTalk.Store.set("profiles",profiles||{})'))throw new Error('profile snapshots are not stored when they arrive');
if(!chats.includes('const isRenderedChatRoute=()=>MiniTalk.Router.current()==="chats"')||chats.includes('if(MiniTalk.Store.get("route")!=="chats")return'))throw new Error('initial Firebase events can render the chat list before the router enters it');
for(const ref of ['js/adapters/auth-api.js?v=64.5.40','js/adapters/realtime.js?v=64.5.47'])if(!html.includes(ref))throw new Error(`stale profile/auth cache version: ${ref}`);
console.log('PROFILE_FIRST_RENDER_OK');
