const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const service=fs.readFileSync(path.join(root,'js/shopping/store-service.js'),'utf8');
const realtime=fs.readFileSync(path.join(root,'js/adapters/realtime.js'),'utf8');
const ui=fs.readFileSync(path.join(root,'js/features/shopping.js'),'utf8');
const css=fs.readFileSync(path.join(root,'css/features/shopping-store.css'),'utf8');
const math=fs.readFileSync(path.join(root,'js/tasks/daily-math-quest.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const server=fs.readFileSync(path.join(root,'docs/apps-script/coin-shopping-extension.gs'),'utf8');
const clarity=fs.readFileSync(path.join(root,'css/features/display-clarity.css'),'utf8');
if(service.includes('const balance = await MiniTalk.Economy.CoinWallet.refresh(true)'))throw new Error('redundant pre-purchase balance request remains');
if(!service.includes('result.product?.imageUrl')||!service.includes('writeCatalog('))throw new Error('optimistic saved-image catalog update is missing');
if(!realtime.includes('pendingSync:true')||!realtime.includes('syncPendingShopInventory'))throw new Error('purchased inventory fallback/sync queue is missing');
if(!realtime.includes('firebaseAuthenticated&&!shopInventoryFallback'))throw new Error('protected shop inventory writes are not guarded by Firebase authentication');
if(!ui.includes('data.length > 7200')||!server.includes('SHOP_IMAGE_MAX_CHARS = 7200'))throw new Error('client/server product image limits do not match');
if(!server.includes('createTextFinder')||server.includes('SpreadsheetApp.flush();'))throw new Error('slow purchase-log scan or redundant spreadsheet flush remains');
if(!service.includes('CATALOG_CACHE_KEY')||!service.includes('refreshCatalog(true)'))throw new Error('startup catalog cache/prefetch is missing');
if(!service.includes('MiniTalk.AuthApi.shopGift')||!server.includes('function handleShopGift'))throw new Error('server-mediated gift flow is missing');
if(!service.includes('notifyGift')||!server.includes('giftedAt'))throw new Error('gift receipt notification metadata is missing');
if(ui.includes('관리자가 상품을 등록하면')||!ui.includes('상점을 준비하고 있어요'))throw new Error('empty shop copy is not clean');
if(!css.includes('transform: translate(-50%, -50%) rotate(45deg)')||!css.includes('.shop-market-hero { grid-template-columns: 40px minmax(0, 1fr) auto')||!css.includes('.shop-market-count { justify-self: end; margin: 0;')||!css.includes('.shop-product-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px;')||!css.includes('.shop-product-card { min-height: 0; grid-template-columns: 1fr;'))throw new Error('shop hero icon alignment or compact mobile one-row layout is stale');
if(!css.includes('.shop-inventory-fab b { flex: 0 0 18px')||!css.includes('margin: 0; padding: 0'))throw new Error('inventory count badge alignment is stale');
if(!ui.includes('modal-close-button')||!math.includes('icon: "123"')||math.includes('icon: "∑"'))throw new Error('inventory close or elementary math icon polish is missing');
if(!clarity.includes('grid-template-rows: minmax(0, 1fr) 56px')||!clarity.includes('min-height: 56px'))throw new Error('last-loaded clarity CSS still overrides the compact bottom navigation');
if(!service.includes('sameValue')||!ui.includes('preserveScroll: true')||!ui.includes('animate: false')||!ui.includes('clearTimeout(refreshTimer)')||!ui.includes('function patchVisible(host)'))throw new Error('unchanged shop polling can still redraw or jump the whole view');
if(!service.includes('MiniTalk.Realtime.useShopInventory(id,usedAt)'))throw new Error('used state is not synchronized to Firebase inventory with the authoritative timestamp');
if(!service.includes('MiniTalk.Realtime.removeShopInventory?.(id,current.user_id)')||!service.includes('notifyCommandTargets?.([target.user_id])')||!server.includes('"SHOP_GIFT"'))throw new Error('gift source cleanup or recipient wake-up is missing');
if(!ui.includes('button?.disabled')||!ui.includes('button.textContent = "처리 중"'))throw new Error('duplicate inventory use clicks are not blocked');
if(!html.includes('css/features/shopping-store.css?v=64.5.18')||!html.includes('css/features/display-clarity.css?v=64.5.6')||!html.includes('js/features/shopping.js?v=64.5.42')||!html.includes('js/shopping/store-service.js?v=64.5.25')||!html.includes('js/tasks/daily-math-quest.js?v=64.5.7'))throw new Error('shopping or math cache versions are stale');

if(!service.includes('async function randomPurchase()')||!ui.includes('openRandomPurchase()')||!ui.includes('한 번 더 누르면 바로 뽑아요')||!ui.includes('setTimeout(movePrizeToInventory,1100)'))throw new Error('single-spin random purchase client flow is missing');
if(!server.includes('SHOP_RANDOM_PURCHASE_PRICE = 3')||!server.includes('function pickWeightedShopProduct_')||!server.includes('random_purchase'))throw new Error('server-authoritative random purchase is missing');
if(!css.includes('.shop-random-overlay')||!css.includes('shop-random-confetti')||!css.includes('shop-random-arrived'))throw new Error('random purchase reel/result/inventory animation CSS is missing');
console.log('SHOPPING_RELIABILITY_OK');
