const fs=require("fs"),path=require("path");
const root=path.resolve(__dirname,".."),read=p=>fs.readFileSync(path.join(root,p),"utf8");
const realtime=read("js/adapters/realtime.js"),tasks=read("js/tasks/task-service.js"),taskFeature=read("js/features/tasks.js"),admin=read("js/features/admin.js"),shop=read("js/shopping/store-service.js"),feed=read("js/features/feed.js"),chats=read("js/features/chats.js"),index=read("index.html"),sw=read("sw.js"),app=read("js/app.js");
if(!realtime.includes('signals/${commandSignalRoom(user.user_id)}/wakeup')||!realtime.includes('pollServerCommands()}'))throw new Error("Firebase wakeup listener is missing");
if(!realtime.includes('setInterval(pollServerCommands,10000)'))throw new Error("Apps Script command safety polling was not restored");
if(!tasks.includes('pollTimer')||!tasks.includes('setInterval(() => refresh(true).catch(() => {}), 30000)'))throw new Error("Apps Script task safety polling was not restored");
if(!tasks.includes('async function enter()')||!taskFeature.includes('TaskService?.enter?.()')||!taskFeature.includes('leave(){entered=false;}'))throw new Error("task route-entry recovery refresh is missing");
if(!admin.includes('const fallback=setInterval')||!admin.includes('30000')||!admin.includes('tasks:admin-refresh'))throw new Error("admin task review must keep signal plus Apps Script safety refresh");
if(!shop.includes('async function enter()')||shop.includes('setInterval(()=>refreshInventory(true).catch(()=>{}),15000)')||!shop.includes('SHOP_DELIVERY_COMPLETED'))throw new Error("shopping signal-driven refresh is incomplete");
if(feed.includes('render(MiniTalk.UI.Dom.byId("viewHost"))'))throw new Error("feed changes still trigger full-screen render");
if(!chats.includes('startRoomListSubscription')||!chats.includes('stopRoomListSubscription'))throw new Error("room list is not route-scoped");
for(const ref of ['realtime.js?v=64.5.47','task-service.js?v=64.5.26','features/tasks.js?v=64.5.4','features/admin.js?v=64.5.38','app.js?v=64.5.46'])if(!index.includes(ref))throw new Error(`cache-busted signal-idle asset missing: ${ref}`);
if(!sw.includes('moaru-moa-dialogue-fusion-final')||!app.includes('sw.js?v=64.5.60'))throw new Error("signal-idle service worker cache bump missing");
console.log("FIREBASE_IDLE_APPS_SAFETY_OK");
