const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const realtime=read('js/adapters/realtime.js'),feed=read('js/features/feed.js'),tools=read('js/features/tools.js'),friday=read('js/tasks/friday-grade6-mission.js'),css=read('css/features/feed-classinfo-weekly.css'),index=read('index.html'),sw=read('sw.js'),app=read('js/app.js');
if(realtime.includes('limitToLast(keep+50).once("value")'))throw new Error('message pruning still redownloads recent message bodies');
if(!realtime.includes('shallow=true')||!realtime.includes('pruneLastAt')||!realtime.includes('limitToFirst(excess)'))throw new Error('low-download message pruning is incomplete');
if(!realtime.includes('child_added')||!realtime.includes('child_changed')||!realtime.includes('presenceCache')||!realtime.includes('roomsCache'))throw new Error('room/presence child-event optimization is missing');
if(!realtime.includes('cloudSubscribeChildren'))throw new Error('child subscription adapter is missing');
if(realtime.includes('const snap=await ref.once("value"),saved='))throw new Error('sendMessage still re-downloads the message immediately after writing');
if(!realtime.includes('방금 쓴 메시지를 Firebase에서 다시 읽지 않습니다'))throw new Error('no-readback send path is missing');
if(realtime.includes('bindFirstValue(db.ref(MiniTalkConfig.paths.legacyProfiles)')||realtime.includes('bindFirstValue(db.ref(MiniTalkConfig.paths.profiles)'))throw new Error('profile lists still use whole-value live subscriptions');
if(!realtime.includes('startProfileCollection(legacyProfilesRef,"legacy"')||!realtime.includes('startProfileCollection(currentProfilesRef,"current"')||!realtime.includes('orderByChild("updatedAt").startAt(latest+1)'))throw new Error('profile cache/delta optimization is incomplete');
if(feed.includes('cloudSubscribe(STATE_PATH'))throw new Error('feed still subscribes to the entire feedState');
for(const required of ['cloudSubscribeDelta(POSTS_PATH','TOTALS_PATH','VIDEO_LIMIT=700*1024','feed-fab','video-gated','leave:stopSub'])if(!feed.includes(required))throw new Error(`feed optimization missing: ${required}`);
for(const removed of ['id: "notifications"','id: "timer"','id: "layout"'])if(tools.includes(removed))throw new Error(`removed tool still visible: ${removed}`);
for(const required of ['오늘의 타로','알람','닮은 생물 찾기','페이스 체인지','오늘의 시간표','오늘의 급식표'])if(!tools.includes(required))throw new Error(`expected tool missing: ${required}`);
if(friday.includes('평소에는 잠겨 있어요')||friday.includes('text:info.open?"시작":"잠김"'))throw new Error('old Friday mission lock copy/button remains');
for(const required of ['friday-lock-overlay','주간 미션','80점 이상'])if(!friday.includes(required))throw new Error(`Friday mission polish missing: ${required}`);
for(const required of ['.feed-fab','.feed-heart-total','.friday-lock-overlay','.video-gated'])if(!css.includes(required))throw new Error(`new UI style missing: ${required}`);
for(const required of ['feed-classinfo-weekly.css?v=65.0.31','realtime.js?v=64.5.47','friday-grade6-mission.js?v=65.0.19','feed.js?v=65.0.21','features/tools.js?v=64.5'])if(!index.includes(required))throw new Error(`cache-busted asset missing: ${required}`);
if(!sw.includes('moaru-moa-dialogue-fusion-final')||!app.includes('sw.js?v=64.5.60'))throw new Error('service worker cache bump missing');
console.log('TRAFFIC_UI_POLISH_OK');
