// Generated combat effect animation sheets, sampled once to the game's pixel grid.
export const CombatEffects={
 frames:new Map(),ready:false,
 async load(spec){if(!spec)return;const factory=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c;};const images={};await Promise.all(spec.sheets.map(s=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{images[s.id]=image;resolve();};image.onerror=()=>reject(Error('Effect asset '+s.id));image.src=s.src.startsWith('data:')?s.src:'assets/'+s.src;})));this.install(spec,images,factory);},
 install(spec,images,factory){this.frames.clear();for(const sheet of spec.sheets){const image=images[sheet.id];for(let row=0;row<sheet.rows.length;row++){if(sheet.rows[row]==='bread')continue;const frames=[];for(let col=0;col<4;col++){const c=factory(64,64),g=c.getContext('2d');g.imageSmoothingEnabled=false;const rect=sheet.rect||[0,0,image.width,image.height];g.drawImage(image,rect[0]+col*rect[2]/4,rect[1]+row*rect[3]/sheet.rows.length,rect[2]/4,rect[3]/sheet.rows.length,0,0,64,64);if(sheet.rows[row]==='breadrise'){const pixels=g.getImageData(0,0,64,64).data;let bottom=0,top=64;for(let y=0;y<64;y++)for(let x=25;x<39;x++)if(pixels[(y*64+x)*4+3]>200){bottom=Math.max(bottom,y);top=Math.min(top,y);}c.groundY=bottom;c.groundTop=top;}frames.push(c);}frames.maxRadius=1;frames.halfWidth=1;for(const c of frames){const pixels=c.getContext('2d').getImageData(0,0,64,64).data;for(let y=0;y<64;y++)for(let x=0;x<64;x++)if(pixels[(y*64+x)*4+3]>200){frames.maxRadius=Math.max(frames.maxRadius,Math.hypot(x-32,y-32)+1);frames.halfWidth=Math.max(frames.halfWidth,Math.abs(x-32)+1);}}this.frames.set(sheet.rows[row],frames);}}this.ready=true;},
 key(f){const kind=f.kind,material=f.feedback?.material;if(kind==='shoot'&&f.weapon!=='bow')return material==='paper'?'pages':'runes';if(kind==='cast')return material==='paper'?'pages':material==='magic'?'runes':null;if(kind==='panclang'||kind==='pulse')return 'metalclang';if(kind==='slash'&&material==='pan')return 'metalclang';if(kind==='slash'&&['wood_axe','wood_mallet','giant_paddle'].includes(f.appearance))return 'woodchips';if((kind==='slash'||kind==='slam'||kind==='spin')&&material==='candy')return 'candy';if((kind==='slash'||kind==='slam'||kind==='spin')&&material==='bread')return 'crumbs';if(kind==='slash'){if(material==='bread')return 'crumbs';if(material==='candy')return 'candy';return f.weapon==='dagger'?'thrust':f.weapon==='axe'?'chop':f.weapon==='mace'||f.weapon==='hammer'?'slam':'slash';}return ({spin:'whirlwind',slam:'slam',shoot:'release',fireball:'fire',meteor:'meteor',thunder:'thunder',lightning:'thunder',poison:'poison',acid:'acid',vines:'vines',heal:'heal',moonheal:'heal',ward:'heal',breadrise:'breadrise',candyburst:'candy',clockwave:'clock',bladewave:'moon',crescent:'moon',phoenix:'phoenix'})[kind];},
 layout(f){const key=this.key(f),frames=this.frames.get(key);if(!frames)return null;const radius=Math.max(.05,f.radius||1),sweep=f.kind==='slash',offset=sweep?key==='crumbs'?Math.min(1.5,radius*.4):radius*.5:0,available=sweep?Math.min(offset,radius-offset):radius,unit=key==='breadrise'?Math.min(1/16,radius/frames.halfWidth):key==='crumbs'?Math.min(1/16,available/frames.maxRadius):available/frames.maxRadius;return {key,frames,radius,offset,unit,maxExtent:offset+unit*frames.maxRadius};},
 paint(ctx,f,time){const layout=this.layout(f);if(!layout)return false;const {key,frames,radius,offset,unit}=layout,progress=Math.max(0,Math.min(.999,1-f.life/f.maxLife)),frame=key==='breadrise'?frames[2]:frames[Math.floor(progress*4)],directional=['slash','thrust','chop','release','moon','clock','phoenix','crumbs','woodchips'].includes(key);ctx.save();ctx.imageSmoothingEnabled=false;ctx.translate(f.x,f.y);
 if(f.kind==='lightning'){const tile=64*.8/frames.halfWidth;ctx.rotate(f.angle||0);for(let x=tile/2;x<=radius-tile/2;x+=tile*.7){ctx.save();ctx.translate(x,0);ctx.rotate(-Math.PI/2);const scale=.8/frames.halfWidth;ctx.drawImage(frame,-32*scale,-32*scale,64*scale,64*scale);ctx.restore();}ctx.restore();return true;}
 if(offset)ctx.translate(Math.cos(f.angle||0)*offset,Math.sin(f.angle||0)*offset);if(directional)ctx.rotate(f.angle||0);ctx.globalAlpha*=Math.min(1,(1-progress)*3);
 if(key==='breadrise'){const rise=progress<.32?progress/.32:progress<.7?1:Math.max(0,(1-progress)/.3);ctx.beginPath();ctx.rect(-32*unit,-64*unit,64*unit,64*unit);ctx.clip();ctx.translate(0,Math.round((1-rise)*((frame.groundY||58)-(frame.groundTop||8)+1))*unit);}
 ctx.drawImage(frame,-32*unit,key==='breadrise'?-(frame.groundY||58)*unit:-32*unit,64*unit,64*unit);ctx.restore();return true;},
 projectile(ctx,p,time){const key=p.kind==='heal'?'heal':p.kind==='phoenix'?'phoenix':p.kind==='fireball'?'fire':['bladewave','crescent','star'].includes(p.kind)?'moon':p.kind==='clockwave'?'clock':p.kind==='thorn'?'vines':p.kind==='lightning'?'thunder':p.kind==='magic'?({meteor:'meteor',poison:'poison',acid:'acid',thunder:'thunder',lightning:'thunder',fireball:'fire',vines:'vines'})[p.weapon]:null,frames=this.frames.get(key);if(!frames)return false;ctx.save();ctx.imageSmoothingEnabled=false;ctx.translate(p.x,p.y);ctx.rotate(p.angle||0);const frame=frames[1+Math.floor(time*10)%2],size=Math.min(p.kind==='phoenix'?2:p.kind==='magic'?1.6:1.8,1.2*64/(frames.maxRadius*2));if(key==='thunder')ctx.rotate(-Math.PI/2);ctx.drawImage(frame,-size/2,-size/2,size,size);ctx.restore();return true;}
};
