import {CharacterRenderer} from './character-runtime.mjs?v=20261009-final-equipment';
import {SkillPreview} from './skill-preview.mjs?v=20261009-final-equipment';
import {equipmentTrait} from './shared/equipment-traits.mjs';
import {WEAPONS} from './shared/catalog.mjs';
const canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d'),characters=new CharacterRenderer(canvas),controls=document.querySelector('#controls'),status=document.querySelector('#status');
let preview,paused=false,walking=false,guarding=false,special=false,battle=false,needsPaint=true,last=performance.now(),frameCount=0;
const selections={};
let inspectBody=false,inspectFeet=false;
const originalRig=characters.rig.bind(characters);
characters.rig=(...args)=>{const rig=originalRig(...args);if(inspectBody||inspectFeet)for(const dir of ['front','side','back']){const old=rig.sprites[dir].head,blank=characters.factory(old.width,old.height);blank.trimBottom=old.trimBottom;rig.sprites[dir].head=blank;rig.expressions[dir]=null;if(inspectFeet)for(const name of ['torso','leftArm','rightArm']){const a=rig.sprites[dir][name],im=a.image||a,b=characters.factory(im.width,im.height);rig.sprites[dir][name]=a.image?{...a,image:b}:b;}}return rig;};
const bodyButton=document.createElement('button');bodyButton.textContent='몸통·팔 연결 확인';bodyButton.onclick=()=>{inspectBody=!inspectBody;inspectFeet=false;characters.actors.clear();bodyButton.textContent=inspectBody?'전체 캐릭터 보기':'몸통·팔 연결 확인';footButton.textContent='신발·바짓단 확인';needsPaint=true;};document.querySelector('#walk').before(bodyButton);
const footButton=document.createElement('button');footButton.textContent='신발·바짓단 확인';footButton.onclick=()=>{inspectFeet=!inspectFeet;inspectBody=false;characters.actors.clear();footButton.textContent=inspectFeet?'전체 캐릭터 보기':'신발·바짓단 확인';bodyButton.textContent='몸통·팔 연결 확인';needsPaint=true;};document.querySelector('#walk').before(footButton);
function select(label,key,entries,value){const l=document.createElement('label');l.append(label);const s=document.createElement('select');s.setAttribute('aria-label',label);for(const [id,name]of entries){const o=document.createElement('option');o.value=id;o.textContent=name;s.append(o);}s.value=value;s.onchange=reset;l.append(s);controls.append(l);selections[key]=s;}
try{
 const m=await(await fetch('assets/manifest.json?v=20261009-final-equipment')).json();await characters.load(m.characters);preview=new SkillPreview(characters);
 select('얼굴','head',Array.from({length:8},(_,i)=>['p'+(i+1),'캐릭터 '+(i+1)]),'p1');
 for(const [key,label,value]of [['main','무기','longsword'],['helmet','머리','guard_helm'],['armor','갑옷','guard_plate'],['boots','신발','guard_boots'],['off','방패 / 랜턴','moon_lamp']])select(label,key,[...(key==='main'?[]:[['','없음']]),...preview.catalog.filter(i=>(i.kind===key||key==='off'&&i.type==='lantern')).map(i=>[i.appearance,i.name])],value);
 select('방향','direction',[['0','오른쪽'],[String(Math.PI),'왼쪽'],[String(Math.PI/2),'앞'],[String(-Math.PI/2),'뒤']],String(Math.PI/2));
 const originalSelect=preview.select.bind(preview);preview.select=(...args)=>{const result=originalSelect(...args);apply();return result;};
 const draw=characters.draw.bind(characters);characters.draw=(c,e,t,moving,index,visualTime)=>draw(c,inspectFeet?{...e,equipment:{...e.equipment,main:null,off:null,armor:null,helmet:null}}:e,t,moving||(walking&&e.id==='preview-hero'),index,visualTime);
 reset();canvas.dataset.preview='ready';
 const presets=document.createElement('nav');for(const [label,armor,boots]of [['판금','guard_plate','guard_boots'],['가죽옷','ranger_leather','worn_shoes'],['천옷','moon_robe','moon_boots'],['왕실 망토','royal_cloak','swan_shoes']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{selections.armor.value=armor;selections.boots.value=boots;setBattle(false);reset();};presets.append(b);}controls.after(presets);
}catch(e){status.textContent='로딩 실패: '+e.message;canvas.dataset.preview='error';throw e;}
function apply(){const h=preview.hero;h.headId=selections.head.value;h.equipment={};for(const k of ['main','helmet','armor','boots','off']){const item=preview.catalog.find(i=>(i.kind===k||k==='off'&&i.type==='lantern')&&i.appearance===selections[k].value);if(item)h.equipment[k]=structuredClone(item);}if(WEAPONS[h.equipment.main?.type]?.hands===2){delete h.equipment.off;selections.off.value='';}preview.guardHitAt=0;preview.target.equipment={main:structuredClone(preview.catalog.find(i=>i.appearance==="longsword"))};preview.target.hp=preview.target.maxHp=10000;const descriptions=Object.values(h.equipment).map(equipmentTrait).filter(Boolean).map(t=>t.detail);status.textContent=descriptions.join(' · ')||'머리와 팔 파츠가 움직임에 맞춰 조립됩니다.';}
function reset(){needsPaint=true;if(preview)preview.select(selections.main.value,special,Number(selections.direction.value));}
function setBattle(value){needsPaint=true;battle=value;document.querySelector('#view').textContent=battle?'네 방향 착용 보기':'전투 시험 보기';}
document.querySelector('#view').onclick=()=>setBattle(!battle);
document.querySelector('#guard').onclick=()=>{guarding=!guarding;setBattle(true);reset();};document.querySelector('#basic').onclick=()=>{special=false;setBattle(true);reset();};document.querySelector('#special').onclick=()=>{special=true;setBattle(true);reset();};document.querySelector('#walk').onclick=()=>{walking=!walking;needsPaint=true;};document.querySelector('#pause').onclick=e=>{paused=!paused;e.target.textContent=paused?'재생':'일시정지';};
function fitting(){const width=canvas.width,height=canvas.height,g=preview.game;ctx.resetTransform();ctx.fillStyle='#17232d';ctx.fillRect(0,0,width,height);const directions=[Math.PI/2,Math.PI,-Math.PI/2,0],labels=['앞','왼쪽','뒤','오른쪽'];for(let i=0;i<4;i++){const center=width*(i+.5)/4;ctx.fillStyle='#dbeaf5';ctx.textAlign='center';ctx.font='bold 24px system-ui';ctx.fillText(labels[i],center,65);if(i){ctx.strokeStyle='#31424f';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(width*i/4,95);ctx.lineTo(width*i/4,height-25);ctx.stroke();}ctx.save();ctx.translate(center,height*.76);ctx.scale(inspectFeet?220:inspectBody?95:42,inspectFeet?220:inspectBody?95:42);characters.draw(ctx,{...preview.hero,id:'fit-view-'+i,x:0,y:0,facing:directions[i],poseTime:g.time},g.time,walking,i,preview.clock);ctx.restore();}ctx.textAlign='left';}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(preview){preview.walking=walking;preview.guardPreview=guarding&&battle;if(!paused)preview.advance(dt);if(!paused||needsPaint){if(battle)preview.paint(ctx,canvas.width,canvas.height);else fitting();needsPaint=false;canvas.dataset.view=battle?'combat':'four-directions';canvas.dataset.frames=String(++frameCount);}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
