import {writeFileSync} from 'node:fs';
import {createMatchItemCatalog,WEAPONS,AFFIX_NAMES} from './shared/catalog.mjs';
import {DungeonGame} from './shared/engine.mjs';
import {StateEncoder} from './shared/state-codec.mjs';
const categories={main:'무기',helmet:'머리 장비',armor:'몸통 장비',boots:'신발',off:'보조 장비',lantern:'랜턴'};
const catalog=createMatchItemCatalog(42);let doc='# 고유 아이템 목록\n\n이미지 생성 전 게임 데이터 목록입니다. 무기·머리·몸통·신발·보조·랜턴 각각 N 3 / R 5 / SR 12 / SSR 5, 총 150종입니다. 장착 슬롯은 5개이며 보조와 랜턴은 왼손 슬롯을 공유합니다.\n\n각 판의 시드로 능력치와 추가 효과를 배정합니다. 일반 공격과 물리 특수 공격의 무기 공격력은 최소~최대 사이에서 공격당 한 번 추첨합니다. 방어·체력·민첩과 발동 확률은 한 판 안에서 유지됩니다. 아래는 시드 42의 예시입니다.\n\n';
for(const [kind,title] of Object.entries(categories)){doc+='## '+title+'\n\n| 등급 | 이름 | 계열 / 외형 | 능력치 범위 | 효과 예시 | 짧은 이야기 |\n|---|---|---|---|---|---|\n';for(const it of catalog.filter(i=>i.kind===kind)){const ranges=Object.entries(it.ranges).map(([k,r])=>({attack:'공격',defense:'방어',hp:'체력',agility:'민첩'}[k])+` ${r[0]}~${r[1]}`).join(', '),effects=it.affixes.map(a=>(AFFIX_NAMES[a.key]||a.key)+' '+(a.charges===null?Math.round(a.chance*100)+'%':a.maxCharges+'회')).join(', ')||'능력치 보너스';doc+=`| ${['N','R','SR','SSR'][it.tier]} | ${it.name} | ${WEAPONS[it.type]?.name||title} / ${it.visual.shape}, ${it.visual.profile} | ${ranges} | ${effects} | ${it.story} |\n`;}doc+='\n';}
writeFileSync(new URL('./ITEM-CATALOG.md',import.meta.url),doc);
const report=[];for(const bots of [1,3,5,7])for(const seed of [1,7,42,99]){const g=new DungeonGame({mode:'dungeon',role:'master',bots,seed});g.autoBuild();g.command('local',{action:'startRaid'});for(let i=0;i<6000&&!g.result;i++)g.step(.05);report.push({bots,seed,time:+g.time.toFixed(1),room:g.currentRoom+1,winner:g.result?.winner||'정체',living:g.entities.filter(e=>e.kind==='player'&&!e.dead).length,chests:g.chests.filter(c=>c.opened).length});}
const net=new DungeonGame({mode:'dungeon',bots:7,seed:42}),encoder=new StateEncoder();encoder.encode(net.snapshot('local'));let full=0,delta=0;
for(let i=0;i<100;i++){net.input('local',{mx:1,aimX:50,aimY:12});net.step(.05);const state=net.snapshot('local');full+=Buffer.byteLength(JSON.stringify({type:'snapshot',version:1,state}));delta+=Buffer.byteLength(JSON.stringify(encoder.encode(state)));}
let result='# 자동 플레이 및 전송 검증\n\n추천 배치로 AI 모험가 1·3·5·7명, 시드 1·7·42·99를 각각 최대 300초 시뮬레이션했습니다. 수동으로 자원을 모두 사용하는 배치와 인간 조작의 밸런스를 보장하는 결과는 아닙니다.\n\n| 인원 | 시드 | 종료 시간 | 도달 방 | 승자 | 생존 | 연 상자 |\n|---|---|---|---|---|---|---|\n';
for(const r of report)result+=`| ${r.bots} | ${r.seed} | ${r.time}초 | ${r.room} | ${r.winner==='party'?'모험가':r.winner==='master'?'마스터':r.winner} | ${r.living} | ${r.chests} |\n`;
result+=`\n16판 중 정체 ${report.filter(r=>r.winner==='정체').length}판, 모험가 승리 ${report.filter(r=>r.winner==='party').length}판.\n\n동일한 100개 상태를 JSON으로 직렬화했을 때 전체 스냅샷 ${full.toLocaleString()}바이트, 변경분 ${delta.toLocaleString()}바이트 (${Math.round((1-delta/full)*100)}% 감소)였습니다. 초기 상태는 전체 전송합니다. 실제 네트워크 서버 부하 측정은 아니며, 외부 서버는 연결하지 않았습니다.\n\n입력은 최대 20Hz, 변화가 없으면 0.5초 간격 유지 패킷만 전송합니다. 싱글 화면에서는 같은 시뮬레이션 틱의 스냅샷을 재사용합니다. 맵 바닥 이미지는 클라이언트에서 한 번 그린 뒤 캐시합니다. AI 감지는 5Hz이며 경로는 캐시합니다. 조명·음향·파티클·화면 흔들림은 클라이언트 렌더러만 처리합니다.\n`;
writeFileSync(new URL('./VERIFICATION.md',import.meta.url),result);console.log(JSON.stringify({catalog:catalog.length,simulations:report.length,stalls:report.filter(r=>r.winner==='정체').length,partyWins:report.filter(r=>r.winner==='party').length,full,delta}));
